### ISSUE TITLE
riak calls via curator failures after upgrading to Rails 4.2.4

### ISSUE THREAD

**Issue by SavithaK** [braintree/curator#50]
After upgrading to 4.2.4 from 4.1.6, we cannot fetch data by key when we use the default bucket names. I believe this is caused by a change to underscore https://github.com/rails/rails/commit/707dfcdbc36c48af3411b9de08d70757ee4e612f

that fails https://github.com/braintree/curator/blob/master/lib/curator/repository.rb#L35

NoMethodError:
       undefined method `empty?' for TenantMapping:Class
     # /Users/savithak/.rvm/gems/ruby-2.2.3@persona/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:375:in `apply_inflections'
     # /Users/savithak/.rvm/gems/ruby-2.2.3@persona/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:32:in `pluralize'
     # /Users/savithak/.rvm/gems/ruby-2.2.3@persona/gems/activesupport-4.2.4/lib/active_support/inflector/methods.rb:166:in `tableize'
     # /Users/savithak/.rvm/gems/ruby-2.2.3@persona/gems/curator-0.11.0/lib/curator/repository.rb:35:in `default_collection_name'
     # /Users/savithak/.rvm/gems/ruby-2.2.3@persona/gems/curator-0.11.0/lib/curator/repository.rb:31:in `collection_name'
     # /Users/savithak/.rvm/gems/ruby-2.2.3@persona/gems/curator-0.11.0/lib/curator/repository.rb:64:in `find_by_id'

I can try a PR to use class name (to_s) instead in https://github.com/braintree/curator/blob/master/lib/curator/repository.rb#L35. 

Thoughts @pgr0ss?
